// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCR3KdL9YRC6xsj_uUclTP450WwqXxRhV4',
    appId: '1:893826836090:web:5b6258d1ce2a3cf2d1fdc3',
    messagingSenderId: '893826836090',
    projectId: 'testing-aa21c',
    authDomain: 'testing-aa21c.firebaseapp.com',
    storageBucket: 'testing-aa21c.appspot.com',
    measurementId: 'G-ZKMC5YK94D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKsAaz-dMfAldT6JI0UMfPbjd-Tq4yeEQ',
    appId: '1:893826836090:android:f1a5def4dc2d1997d1fdc3',
    messagingSenderId: '893826836090',
    projectId: 'testing-aa21c',
    storageBucket: 'testing-aa21c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHfe2CPWVcygUVFFWUHHE_TIdsR13JVas',
    appId: '1:893826836090:ios:2d1d8f043308e6dfd1fdc3',
    messagingSenderId: '893826836090',
    projectId: 'testing-aa21c',
    storageBucket: 'testing-aa21c.appspot.com',
    androidClientId: '893826836090-0rrm1thltaaiqk9i476l6pm96mff7mjc.apps.googleusercontent.com',
    iosClientId: '893826836090-ls2a172fehtpf0pf49v7e0decok0qata.apps.googleusercontent.com',
    iosBundleId: 'com.Pccoe.canteenApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHfe2CPWVcygUVFFWUHHE_TIdsR13JVas',
    appId: '1:893826836090:ios:2d1d8f043308e6dfd1fdc3',
    messagingSenderId: '893826836090',
    projectId: 'testing-aa21c',
    storageBucket: 'testing-aa21c.appspot.com',
    androidClientId: '893826836090-0rrm1thltaaiqk9i476l6pm96mff7mjc.apps.googleusercontent.com',
    iosClientId: '893826836090-ls2a172fehtpf0pf49v7e0decok0qata.apps.googleusercontent.com',
    iosBundleId: 'com.Pccoe.canteenApp',
  );
}
